### ISSUE TITLE
how to solve?

### ISSUE THREAD

**Issue by huxiaotaostasy** [lbin/DCNv2#11]
[7/7] c++ -MMD -MF /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/vision.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/ubuntu/Downloads/TDAN/DCNv216/src -I/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include -I/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/TH -I/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/anaconda3/envs/python3.7/include/python3.7m -c -c /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp -o /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/cpu/vision.h:2,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:3,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:
/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 ^
In file included from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:0:
/home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h: In function ‘at::Tensor dcn_v2_forward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, int, int, int, int, int, int, int)’:
/home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:25:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     if (input.type().is_cuda())
                    ^
In file included from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/cpu/vision.h:2,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:3,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:
/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
In file included from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:0:
/home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h: In function ‘std::vector<at::Tensor> dcn_v2_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, int, int, int, int, int, int, int)’:
/home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:61:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     if (input.type().is_cuda())
                    ^
In file included from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/cpu/vision.h:2,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:3,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:
/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
In file included from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:0:
/home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h: In function ‘std::tuple<at::Tensor, at::Tensor> dcn_v2_psroi_pooling_forward(const at::Tensor&, const at::Tensor&, const at::Tensor&, int, float, int, int, int, int, int, float)’:
/home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:107:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     if (input.type().is_cuda())
                    ^
In file included from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/cpu/vision.h:2,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:3,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:
/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
In file included from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:0:
/home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h: In function ‘std::tuple<at::Tensor, at::Tensor> dcn_v2_psroi_pooling_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, float, int, int, int, int, int, float)’:
/home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:155:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     if (input.type().is_cuda())
                    ^
In file included from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/cpu/vision.h:2,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/dcn_v2.h:3,
                 from /home/ubuntu/Downloads/TDAN/DCNv216/src/vision.cpp:2:
/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
g++ -pthread -shared -B /home/ubuntu/anaconda3/envs/python3.7/compiler_compat -L/home/ubuntu/anaconda3/envs/python3.7/lib -Wl,-rpath=/home/ubuntu/anaconda3/envs/python3.7/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/vision.o /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/cpu/dcn_v2_im2col_cpu.o /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/cpu/dcn_v2_psroi_pooling_cpu.o /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/cpu/dcn_v2_cpu.o /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/cuda/dcn_v2_cuda.o /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/cuda/dcn_v2_psroi_pooling_cuda.o /home/ubuntu/Downloads/TDAN/DCNv216/build/temp.linux-x86_64-3.7/home/ubuntu/Downloads/TDAN/DCNv216/src/cuda/dcn_v2_im2col_cuda.o -L/home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/_ext.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/_ext.cpython-37m-x86_64-linux-gnu.so -> 
Creating /home/ubuntu/anaconda3/envs/python3.7/lib/python3.7/site-packages/DCNv2.egg-link (link to .)
Adding DCNv2 0.1 to easy-install.pth file

Installed /home/ubuntu/Downloads/TDAN/DCNv216
Processing dependencies for DCNv2==0.1
Finished processing dependencies for DCNv2==0.1

**Comment by lbin** [comment]
I didn't see any error information

**Comment by maazullah96** [comment]
@lbin  I have tried to run DCNV2 it builds successfully but it shows error in importing dcn_v2 or running the test file.
![image](https://user-images.githubusercontent.com/30190807/107502601-b0d88100-6bba-11eb-8e1a-d76fd7ff59cc.png)
