### ISSUE TITLE
nvcc fatal   : Value 'c++14' is not defined for option 'std'

### ISSUE THREAD

**Issue by cps80** [lbin/DCNv2#17]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/disk/chengpeisong/project/LaneAF/models/dla/DCNv2/src -I/home/chengpeisong/anaconda3/envs/laneaf/lib/python3.6/site-packages/torch/include -I/home/chengpeisong/anaconda3/envs/laneaf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chengpeisong/anaconda3/envs/laneaf/lib/python3.6/site-packages/torch/include/TH -I/home/chengpeisong/anaconda3/envs/laneaf/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chengpeisong/anaconda3/envs/laneaf/include/python3.6m -c /home/disk/chengpeisong/project/LaneAF/models/dla/DCNv2/src/cpu/dcn_v2_im2col_cpu.cpp -o build/temp.linux-x86_64-3.6/home/disk/chengpeisong/project/LaneAF/models/dla/DCNv2/src/cpu/dcn_v2_im2col_cpu.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/disk/chengpeisong/project/LaneAF/models/dla/DCNv2/src -I/home/chengpeisong/anaconda3/envs/laneaf/lib/python3.6/site-packages/torch/include -I/home/chengpeisong/anaconda3/envs/laneaf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chengpeisong/anaconda3/envs/laneaf/lib/python3.6/site-packages/torch/include/TH -I/home/chengpeisong/anaconda3/envs/laneaf/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/chengpeisong/anaconda3/envs/laneaf/include/python3.6m -c /home/disk/chengpeisong/project/LaneAF/models/dla/DCNv2/src/cuda/dcn_v2_cuda.cu -o build/temp.linux-x86_64-3.6/home/disk/chengpeisong/project/LaneAF/models/dla/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -ccbin g++ -std=c++14
nvcc fatal   : Value 'c++14' is not defined for option 'std'
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by cps80** [comment]
when 
cd DCNv2 
./make.sh

**Comment by hluo29** [comment]
You can try to check the version of cuda and nvidia driver. This may help you.
