### ISSUE TITLE
Branch:pytorch1.6  RuntimeError:expected scalar type Float but found Half

### ISSUE THREAD

**Issue by ShellyLingling** [lbin/DCNv2#2]
Please help me! 
pytorch version:1.6.0
when I use the @torch.cuda.amp.autocast before "def forward():", this error occurs. 
I don't know how how to solve this problem. 
I couldn't find a substitute for @apex.amp.float_function in pytorch1.6

**Comment by lbin** [comment]
you should install **apex** from nvidia github repo
