### ISSUE TITLE
UserWarning: Error checking compiler version for cl:

### ISSUE THREAD

**Issue by DioMou** [lbin/DCNv2#20]
I am having problems with setup the dcnv2, it gives me the following warning if I run python setup.py build develop. Although the building process successfully finished, but if I try to import _ext, it says `DLL load failed while importing _ext`, so I suspect this is because of the user warning below.
`running build`
`running build_ext`
`cl`(it says this is my printed compiler name but I am not running it on visual studio, this is simply vscode with python 3.8 torch 3.7.0)
`Traceback (most recent call last):`(self printed traceback, start here)
 ` File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\site-packages\torch\utils\cpp_extension.py", line 270, in check_compiler_abi_compatibility
    compiler_info = subprocess.check_output(compiler, stderr=subprocess.STDOUT)`
 ` File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,`
  `File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:`
  `File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,`
  `File "C:\Users\LXAB\anaconda3\envs\mltorch\lib\subprocess.py", line 1311, in _execute_child     
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,`
`FileNotFoundError: [WinError 2] 系统找不到指定的文件。`(means system cannot find file,ends here)
`C:\Users\LXAB\anaconda3\envs\mltorch\lib\site-packages\torch\utils\cpp_extension.py:278: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building '_ext' extension`
I did try to change decode to gbk but does not work. Anybody can help?

**Comment by lbin** [comment]
not test on Windows
