### ISSUE TITLE
有用有用，解决问题了，疯狂安利

### ISSUE THREAD

**Issue by BinLi-git** [lbin/DCNv2#26]
有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利
。。。多谢

**Comment by Themassif** [comment]
> 请问你的配置环境是怎样的呢，我使用的pytorch1.9一直报错

**Comment by Themassif** [comment]
> 有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利 。。。多谢



> 有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利 。。。多谢

请问你的配置环境是怎样的呢，我使用的pytorch1.9一直报错

**Comment by Themassif** [comment]
> 有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利 。。。多谢

请问你的配置环境是怎样的呢，我使用的pytorch1.9一直报错

**Comment by BinLi-git** [comment]
> > 有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利 。。。多谢
> 
> 请问你的配置环境是怎样的呢，我使用的pytorch1.9一直报错

我用的是pytorch1.7那个branch

**Comment by Themassif** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lbin/DCNv2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lbin/DCNv2] 有用有用，解决问题了，疯狂安利 (Issue #26)





   
有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利有用有用，解决问题了，疯狂安利 。。。多谢
  
请问你的配置环境是怎样的呢，我使用的pytorch1.9一直报错
  
我用的是pytorch1.7那个branch
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
