### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by fuzailpalnak** [lbin/DCNv2#36]
```
torchvision               0.8.0
python                    3.8
cudatoolkit               10.2.89
pytorch                   1.7.0           py3.7_cuda10.2.89_cudnn7.6.5_0

```
I get `RuntimeError: Error compiling objects for extension` when i run `make.sh` with torch 1.7, i followed the steps mentioned in [this repo](https://github.com/ifzhang/FairMOT#installation)

**Comment by lbin** [comment]
try this branch https://github.com/lbin/DCNv2/tree/pytorch_1.7 ?

**Comment by fuzailpalnak** [comment]
I tried both branches, `master` and `pytorch_1.7`, the issue still persist.

**Comment by lbin** [comment]
some suggestion: use lts or stable version of pytorch

**Comment by fuzailpalnak** [comment]
Changing the local toolkit version resolved the issue. Thanks for the help
