### ISSUE TITLE
dcn_v2_cuda.obj : error LNK2001: 无法解析的外部符号 cublasSgemv_v2

### ISSUE THREAD

**Issue by sakuraru** [lbin/DCNv2#42]
正在创建库 build\temp.win-amd64-cpython-37\Release\CenterNet\src\lib\models\networks\DCNv2\src\cpu\_ext.cp37-win_amd64.lib 和对象 build\temp.win-amd64-cpython-37\Release\CenterNet\src\lib\models\networks\DCNv2\src\cpu\_ext.cp37-win_amd64.exp
dcn_v2_cuda.obj : error LNK2001: 无法解析的外部符号 cublasSgemv_v2
build\lib.win-amd64-cpython-37\_ext.cp37-win_amd64.pyd : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'D:\\ProgramFiles\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
请问这个问题应该怎么解决呀？

**Comment by lbin** [comment]
使用正确的torch版本和对应的branch
