### ISSUE TITLE
FP16 training error

### ISSUE THREAD

**Issue by qing3** [lbin/DCNv2#8]
Hi, I want to use fp16 to train DCN, but  error "RuntimeError: expected scalar type Float but found Half (data_ptr<float> at /home/amax/.conda/envs/pytorch/lib/python3.6/site-packages/torch/include/ATen/core/TensorMethods.h:5747)" occurs. Do you know the reason? Hope for your reply!

**Comment by qing3** [comment]
Training with FP32 is no problem.

**Comment by lbin** [comment]
pls follow 1.7 branch @qing3
